services:
  inventorydb:
    image: postgres

  cartDb:
    image: postgres
  
  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile

volumes:
    postgres_inventory: