services:
  inventorydb:
    container_name: inventorydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InventoryDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_inventory:/var/lib/postgresql/data

  cartdb:
    container_name: cartdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CartDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_cart:/var/lib/postgresql/data
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  
  inventory.api:
    container_name: inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings_Database=Server=inventorydb;Port=5432;Database=InventoryDb;User Id=postgres;Password=postgres;Include Error Detail=true"
    depends_on:
      - inventorydb
    ports:
      - "6000:8080" # Exposed port for HTTP is 6000 and mapped to 8080 in the container.
      - "6060:8081" # Exposed port for HTTPS is 6060 and mapped to 8081 in the container.
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/ASP.NET/Https:/home/app/.microsoft/https:ro
  
  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings_Database=Server=cartdb;Port=5432;Database=CartDb;User Id=postgres;Password=postgres;Include Error Detail=true"
      - "ConnectionString_Redis=distributedcache:6379"
      - "GrpcSettings_CouponUrl=http://coupon.grpc:8081"
    depends_on:
      - cartdb
      - distributedcache
      - coupon.grpc
    ports:
      - "6001:8080" # Exposed port for HTTP is 6000 and mapped to 8080 in the container.
      - "6061:8081" # Exposed port for HTTPS is 6060 and mapped to 8081 in the container.
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/ASP.NET/Https:/home/app/.microsoft/https:ro 
  
  coupon.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings_Database=Server=localhost;Database=CouponDb;Integrated Security=True;TrustServerCertificate=True;"
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
